#!/bin/sh

DEPLOY_HOST=$(cat ../config/deploy-host)
DEPLOY_PATH=backend

go() {
  case $1 in
    deploy)
      deploy
      ;;
    "")
      print_usage
      exit 1
      ;;
    *)
      echo invalid command: "$1"
      print_usage
      exit 1
      ;;
  esac
}

deploy() {
  set -x
  sbt assembly
  rsync -r -l -t -I --delete -z -h target/scala-3.1.1/Darts-Backend-assembly-0.1.0.jar "$DEPLOY_HOST:$DEPLOY_PATH/"
  scp -p ../config/controller-device "$DEPLOY_HOST:$DEPLOY_PATH/"
  ssh "$DEPLOY_HOST" << +
  set -x
  sudo systemctl restart darts
+
}

print_usage() {
  echo usage: "$0" \<command\>
}

error() {
  echo "$1"
  exit 1
}

go "$1"
