#!/bin/sh

BOARD=arduino:avr:micro
PROJECT_NAME=DartsController

DARTBOARD=$(cat dartboard)

DEPLOY_HOST=$(cat deploy-host)
DEPLOY_DEVICE=$(cat deploy-device)
DEPLOY_PATH=controller

go() {
  case $1 in
    build)
      build
      ;;
    deploy)
      deploy
      ;;
    "")
      print_usage
      exit 1
      ;;
    *)
      echo invalid command: "$1"
      print_usage
      exit 1
      ;;
  esac
}

build() {
  set -x
  arduino-cli compile -b $BOARD --build-property "build.extra_flags=\"-DDARTBOARD_$DARTBOARD\"" $PROJECT_NAME
}

deploy() {
  set -x
  scp -rp $PROJECT_NAME "$DEPLOY_HOST":$DEPLOY_PATH/
  ssh "$DEPLOY_HOST" << +
  set -x
  arduino-cli compile -b $BOARD --build-property "build.extra_flags=\"-DDARTBOARD_$DARTBOARD\"" $DEPLOY_PATH/$PROJECT_NAME || { { set +x; } 2> /dev/null; exit 1; }
  arduino-cli upload -v -p $DEPLOY_DEVICE -b $BOARD $DEPLOY_PATH/$PROJECT_NAME
+
}

print_usage() {
  echo usage: "$0" \<command\>
}

error() {
  echo "$1"
  exit 1
}

go "$1"
