#!/bin/sh

BOARD=arduino:avr:micro
PROJECT_NAME=DartsController

DARTBOARD=$(cat ../config/dartboard)

# {build.usb_flags} was copied from boards.txt for the arduino micro b/c build.extra_flags will be overwritten
# this might fail if we ever use another arduino board
BUILD_EXTRA_FLAGS="{build.usb_flags} -DDARTBOARD_$DARTBOARD"

DEPLOY_HOST=$(cat ../config/deploy-host)
DEPLOY_DEVICE=$(cat ../config/controller-device)
DEPLOY_PATH=controller

go() {
  case $1 in
    build)
      build
      ;;
    deploy)
      deploy
      ;;
    "")
      print_usage
      exit 1
      ;;
    *)
      echo invalid command: "$1"
      print_usage
      exit 1
      ;;
  esac
}

build() {
  set -x
  arduino-cli compile -b $BOARD --build-property "build.extra_flags=$BUILD_EXTRA_FLAGS" $PROJECT_NAME
}

deploy() {
  set -x
  rsync -r -l -t -I --delete -z -h $PROJECT_NAME "$DEPLOY_HOST:$DEPLOY_PATH/"
  ssh "$DEPLOY_HOST" << +
  set -x
  arduino-cli compile -b $BOARD --build-property "build.extra_flags=$BUILD_EXTRA_FLAGS" $DEPLOY_PATH/$PROJECT_NAME || { { set +x; } 2> /dev/null; exit 1; }
  arduino-cli upload -v -p $DEPLOY_DEVICE -b $BOARD $DEPLOY_PATH/$PROJECT_NAME
+
}

print_usage() {
  echo usage: "$0" \<command\>
}

error() {
  echo "$1"
  exit 1
}

go "$1"
