#!/bin/sh

BOARD=arduino:avr:nano:cpu=atmega328old
PROJECT_NAME=DartsController

DEPLOY_HOST=$(cat deploy-host)
DEPLOY_DEVICE=$(cat deploy-device)
DEPLOY_PATH=controller

go() {
  case $1 in
    build)
      build
      ;;
    deploy)
      deploy
      ;;
    "")
      print_usage
      exit 1
      ;;
    *)
      echo invalid command: "$1"
      print_usage
      exit 1
      ;;
  esac
}

build() {
  arduino-cli compile -b $BOARD $PROJECT_NAME
}

deploy() {
  scp -rp $PROJECT_NAME "$DEPLOY_HOST":$DEPLOY_PATH/$PROJECT_NAME
  ssh "$DEPLOY_HOST" << +
  arduino-cli compile -b $BOARD $DEPLOY_PATH/$PROJECT_NAME
  arduino-cli upload -v -p $DEPLOY_DEVICE -b $BOARD $DEPLOY_PATH/$PROJECT_NAME
+
}

print_usage() {
  echo usage: "$0" \<command\>
}

error() {
  echo "$1"
  exit 1
}

go "$1"
